# Generated by Django 5.1 on 2024-11-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sheets', models.IntegerField(verbose_name='枚数')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
            ],
            options={
                'verbose_name': '同意説明書（カラー）',
                'verbose_name_plural': '同意説明書（カラー）',
            },
        ),
        migrations.CreateModel(
            name='AgreementMonochrome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sheets', models.IntegerField(verbose_name='枚数')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
            ],
            options={
                'verbose_name': '同意説明書（モノクロ）',
                'verbose_name_plural': '同意説明書（モノクロ）',
            },
        ),
        migrations.CreateModel(
            name='CaseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sheets', models.IntegerField(verbose_name='枚数')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
            ],
            options={
                'verbose_name': 'ケースカード（症例報告書）',
                'verbose_name_plural': 'ケースカード（症例報告書）',
            },
        ),
        migrations.CreateModel(
            name='Chiken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sheets', models.IntegerField(verbose_name='枚数')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
            ],
            options={
                'verbose_name': '治験実施計画書',
                'verbose_name_plural': '治験実施計画書',
            },
        ),
        migrations.CreateModel(
            name='Fukuyaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sheets', models.IntegerField(verbose_name='枚数')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
            ],
            options={
                'verbose_name': '服薬日誌',
                'verbose_name_plural': '服薬日誌',
            },
        ),
    ]
