# Generated by Django 5.1 on 2025-02-19 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=5, unique=True, verbose_name='注文番号')),
                ('product_type', models.CharField(choices=[('consent-color', '同意説明書（カラー）'), ('consent-monochrome', '同意説明書（モノクロ）'), ('case-card', 'ケースカード（症例報告書）'), ('chiken-plan', '治験実施計画書'), ('medication-diary', '服薬日誌'), ('participation-card', '参加カード')], max_length=50, verbose_name='商品の種類')),
                ('invoice_detail', models.CharField(blank=True, max_length=200, null=True, verbose_name='詳細請求書名')),
                ('upload_file', models.CharField(blank=True, max_length=200, null=True, verbose_name='入稿ファイル名')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('content', models.CharField(blank=True, max_length=50, null=True, verbose_name='本文')),
                ('sanka_card_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='参加カードの種類')),
                ('fukusha1', models.CharField(blank=True, max_length=50, null=True, verbose_name='複写1')),
                ('fukusha2', models.CharField(blank=True, max_length=50, null=True, verbose_name='複写2')),
                ('fukusha3', models.CharField(blank=True, max_length=50, null=True, verbose_name='複写3')),
                ('fukusha4', models.CharField(blank=True, max_length=50, null=True, verbose_name='複写なしミシン目')),
                ('fukusha5', models.CharField(blank=True, max_length=50, null=True, verbose_name='複写オプション')),
                ('total_pages', models.CharField(blank=True, max_length=50, null=True, verbose_name='総頁数')),
                ('unit_price', models.IntegerField(verbose_name='単価')),
                ('estimate_result', models.IntegerField(verbose_name='見積もり金額')),
                ('additional_print', models.BooleanField(default=False, verbose_name='追加（増刷）')),
                ('no_holes', models.BooleanField(default=False, verbose_name='2穴不要')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '注文履歴',
                'verbose_name_plural': '注文履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]
