# Generated by Django 5.1 on 2025-02-19 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_rireki', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_histories', to=settings.AUTH_USER_MODEL, verbose_name='担当者'),
            preserve_default=False,
        ),
    ]
