# Generated by Django 5.1 on 2025-02-27 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_rireki', '0002_orderhistory_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='納期'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='yamato_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ヤマト伝票番号'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='product_type',
            field=models.CharField(choices=[('consent-color', '同意説明書（カラー）'), ('consent-monochrome', '同意説明書（モノクロ）'), ('case-card', 'ケースカード（症例報告書）'), ('chiken-plan', '治験実施計画書'), ('medication-diary', '服薬日誌'), ('participation-card', '参加カード'), ('generic', '汎用')], max_length=50, verbose_name='商品の種類'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_histories', to=settings.AUTH_USER_MODEL, verbose_name='担当者'),
        ),
    ]
