# Generated by Django 5.1 on 2025-02-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_rireki', '0003_orderhistory_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='upload_file_timestamped',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='入稿ファイル名(タイムスタンプ付)'),
        ),
    ]
