# Generated by Django 5.1 on 2025-03-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_rireki', '0004_orderhistory_upload_file_timestamped'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='facility',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='施設名'),
        ),
    ]
