# Generated by Django 5.1 on 2025-03-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_rireki', '0005_orderhistory_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='プロジェクト名'),
        ),
    ]
