# Generated by Django 5.1 on 2024-08-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementMonochrome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sheets', models.IntegerField(verbose_name='枚数')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
            ],
            options={
                'verbose_name': '同意説明書モノクロ',
                'verbose_name_plural': '同意説明書モノクロ',
            },
        ),
    ]
