# Generated by Django 5.1 on 2024-10-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_agreementmonochrome'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sheets', models.IntegerField(verbose_name='枚数')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
            ],
            options={
                'verbose_name': 'ケースカード（症例報告書）',
                'verbose_name_plural': 'ケースカード（症例報告書）',
            },
        ),
        migrations.CreateModel(
            name='Chiken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sheets', models.IntegerField(verbose_name='枚数')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
            ],
            options={
                'verbose_name': '治験実施計画書',
                'verbose_name_plural': '治験実施計画書',
            },
        ),
        migrations.AlterModelOptions(
            name='agreementcolor',
            options={'verbose_name': '同意説明書（カラー）', 'verbose_name_plural': '同意説明書（カラー）'},
        ),
        migrations.AlterModelOptions(
            name='agreementmonochrome',
            options={'verbose_name': '同意説明書（モノクロ）', 'verbose_name_plural': '同意説明書（モノクロ）'},
        ),
    ]
